# Generated by Django 4.2.1 on 2023-06-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('customer_id', models.IntegerField()),
                ('cart_id', models.IntegerField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('cart_status', models.CharField(max_length=50)),
                ('total_cost', models.IntegerField()),
                ('items', models.ManyToManyField(to='product.product')),
            ],
        ),
    ]
