# Generated by Django 4.2.1 on 2023-06-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('notification_type', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=255)),
                ('sender_id', models.IntegerField()),
                ('recipient_id', models.IntegerField()),
            ],
        ),
    ]
