# Generated by Django 4.2.1 on 2023-06-21 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('image_url', models.ImageField(upload_to='product_images/')),
            ],
        ),
    ]
